services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 3d1-web
    ports:
      - "5000:80"
    volumes:
      - ./src:/var/www/vhosts/h577143.web300.dogado.net/sites/3d1/local/
      - ./log:/var/www/vhosts/h577143.web300.dogado.net/sites/3d1/log
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/vhosts/h577143.web300.dogado.net/sites/3d1/local/public
    restart: unless-stopped
